version: "3.1"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
    - MonAssistantMedical
    ports:
    - "3000:3000"

#  mysql:
#    image: user/dockercoins_hasher:1.0
#    networks:
#    - MonAssistantMedical

networks:
    MonAssistantMedical: