version: "3.1"

services:
  back:
    image: mam-api
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
        - MonAssistantMedical
    #environment:
    env_file:
        - back.env
    ports:
        - "3000:3000"

  db:
    image: mysql:latest
    networks:
        - MonAssistantMedical
    env_file:
        - db.env
    ports:
        - "3306:3306"
    

networks:
    MonAssistantMedical: